[2025-05-05T14:07:52.230+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T14:07:39.634542+00:00 [queued]>
[2025-05-05T14:07:52.296+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T14:07:39.634542+00:00 [queued]>
[2025-05-05T14:07:52.299+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-05T14:07:52.340+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): entrenar_modelo> on 2025-05-05 14:07:39.634542+00:00
[2025-05-05T14:07:52.378+0000] {standard_task_runner.py:57} INFO - Started process 310 to run task
[2025-05-05T14:07:52.392+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Train_Model', 'entrenar_modelo', 'manual__2025-05-05T14:07:39.634542+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/Train_Data.py', '--cfg-path', '/tmp/tmpxmwmkxt_']
[2025-05-05T14:07:52.404+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask entrenar_modelo
[2025-05-05T14:07:52.685+0000] {task_command.py:416} INFO - Running <TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T14:07:39.634542+00:00 [running]> on host airflow-worker-5c47d7d789-mw9hk
[2025-05-05T14:07:52.945+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Train_Model' AIRFLOW_CTX_TASK_ID='entrenar_modelo' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T14:07:39.634542+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T14:07:39.634542+00:00'
[2025-05-05T14:07:53.100+0000] {logging_mixin.py:154} INFO - Filas le√≠das: 2086
[2025-05-05T14:07:55.384+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:07:55 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-05T14:07:55.725+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:07:55 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/airflow/.local/lib/python3.10/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-05-05T14:07:55.733+0000] {logging_mixin.py:154} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-05-05T14:07:56.011+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.3s
[2025-05-05T14:07:56.611+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.6s
[2025-05-05T14:07:56.790+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T14:07:57.230+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.4s
[2025-05-05T14:07:57.747+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.5s
[2025-05-05T14:07:58.100+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.4s
[2025-05-05T14:07:58.680+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.6s
[2025-05-05T14:08:00.083+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   1.4s
[2025-05-05T14:08:00.578+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.5s
[2025-05-05T14:08:00.933+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.4s
[2025-05-05T14:08:01.367+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.4s
[2025-05-05T14:08:02.199+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.8s
[2025-05-05T14:08:02.856+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.7s
[2025-05-05T14:08:03.502+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.6s
[2025-05-05T14:08:03.870+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.4s
[2025-05-05T14:08:04.772+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.9s
[2025-05-05T14:08:05.838+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   1.1s
[2025-05-05T14:08:07.155+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   1.3s
[2025-05-05T14:08:08.111+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   1.0s
[2025-05-05T14:08:08.811+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.7s
[2025-05-05T14:08:09.446+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.6s
[2025-05-05T14:08:10.386+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.9s
[2025-05-05T14:08:11.227+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.8s
[2025-05-05T14:08:11.926+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.7s
[2025-05-05T14:08:15.325+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-05-05T14:08:17.615+0000] {credentials.py:1124} INFO - Found credentials in environment variables.
[2025-05-05T14:08:19.141+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:08:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/airflow/.local/lib/python3.10/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-05-05T14:08:41.461+0000] {logging_mixin.py:154} WARNING - Registered model 'RandomForestModel' already exists. Creating a new version of this model...
[2025-05-05T14:08:41.618+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:08:41 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RandomForestModel, version 1
[2025-05-05T14:08:41.619+0000] {logging_mixin.py:154} WARNING - Created version '1' of model 'RandomForestModel'.
[2025-05-05T14:09:01.368+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:09:01 INFO mlflow.sklearn.utils: Logging the 5 best runs, 3 runs will be omitted.
[2025-05-05T14:09:02.031+0000] {logging_mixin.py:154} INFO - üèÉ View run ambitious-whale-480 at: http://10.152.183.196:5000/#/experiments/1/runs/d80683fa262e4c02baf0a065aef9c334
[2025-05-05T14:09:02.045+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:09:02.109+0000] {logging_mixin.py:154} INFO - üèÉ View run shivering-skink-261 at: http://10.152.183.196:5000/#/experiments/1/runs/b42ea036f6a5423290fd0e535af7f984
[2025-05-05T14:09:02.113+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:09:02.185+0000] {logging_mixin.py:154} INFO - üèÉ View run sassy-colt-760 at: http://10.152.183.196:5000/#/experiments/1/runs/1ab3a62c66dc441cb5e28eb9e2ebbfd9
[2025-05-05T14:09:02.186+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:09:02.210+0000] {logging_mixin.py:154} INFO - üèÉ View run smiling-asp-955 at: http://10.152.183.196:5000/#/experiments/1/runs/722597ab073d4b0c9fa36b41f4410c2c
[2025-05-05T14:09:02.210+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:09:02.552+0000] {logging_mixin.py:154} INFO - üèÉ View run able-wolf-906 at: http://10.152.183.196:5000/#/experiments/1/runs/eb3cd3bc7a6647e59afa7cb59d1b240e
[2025-05-05T14:09:02.553+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:09:16.584+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:09:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-05T14:09:16.875+0000] {logging_mixin.py:154} INFO - Modelo entrenado con par√°metros: {'max_depth': 10, 'max_features': 10, 'n_estimators': 50}
[2025-05-05T14:09:16.921+0000] {logging_mixin.py:154} INFO - üèÉ View run rf_diabetes_all_varchar at: http://10.152.183.196:5000/#/experiments/1/runs/10d0410bf0a747ec867da76f87943941
[2025-05-05T14:09:16.924+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:09:16.955+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-05T14:09:16.982+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Train_Model, task_id=entrenar_modelo, execution_date=20250505T140739, start_date=20250505T140752, end_date=20250505T140916
[2025-05-05T14:09:17.172+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-05T14:09:17.238+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
