[2025-05-05T19:49:40.130+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T19:49:28.849016+00:00 [queued]>
[2025-05-05T19:49:40.145+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T19:49:28.849016+00:00 [queued]>
[2025-05-05T19:49:40.146+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-05T19:49:40.169+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): entrenar_modelo> on 2025-05-05 19:49:28.849016+00:00
[2025-05-05T19:49:40.208+0000] {standard_task_runner.py:57} INFO - Started process 657 to run task
[2025-05-05T19:49:40.238+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Train_Model', 'entrenar_modelo', 'manual__2025-05-05T19:49:28.849016+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/Train_Data.py', '--cfg-path', '/tmp/tmpvavook4n']
[2025-05-05T19:49:40.247+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask entrenar_modelo
[2025-05-05T19:49:40.448+0000] {task_command.py:416} INFO - Running <TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T19:49:28.849016+00:00 [running]> on host airflow-worker-5c47d7d789-mw9hk
[2025-05-05T19:49:40.845+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Train_Model' AIRFLOW_CTX_TASK_ID='entrenar_modelo' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T19:49:28.849016+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T19:49:28.849016+00:00'
[2025-05-05T19:49:41.070+0000] {logging_mixin.py:154} INFO - Filas le√≠das: 2086
[2025-05-05T19:49:41.970+0000] {logging_mixin.py:154} WARNING - 2025/05/05 19:49:41 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-05T19:49:42.082+0000] {logging_mixin.py:154} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-05-05T19:49:42.316+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:42.686+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.4s
[2025-05-05T19:49:42.914+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:43.409+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.5s
[2025-05-05T19:49:43.806+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.4s
[2025-05-05T19:49:44.150+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T19:49:44.385+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:44.561+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:44.923+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.4s
[2025-05-05T19:49:45.731+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.8s
[2025-05-05T19:49:46.257+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.5s
[2025-05-05T19:49:46.589+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.3s
[2025-05-05T19:49:46.871+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.3s
[2025-05-05T19:49:47.047+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:47.224+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:47.569+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T19:49:48.069+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.5s
[2025-05-05T19:49:48.471+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.4s
[2025-05-05T19:49:48.706+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:48.947+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:49.167+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:49:49.738+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.6s
[2025-05-05T19:49:50.643+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.9s
[2025-05-05T19:49:52.291+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   1.6s
[2025-05-05T19:50:16.904+0000] {logging_mixin.py:154} WARNING - 2025/05/05 19:50:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-05T19:50:17.500+0000] {credentials.py:1124} INFO - Found credentials in environment variables.
[2025-05-05T19:50:19.106+0000] {logging_mixin.py:154} INFO - Modelo entrenado con par√°metros: {'max_depth': 10, 'max_features': 10, 'n_estimators': 50}
[2025-05-05T19:50:19.219+0000] {logging_mixin.py:154} WARNING - Registered model 'RandomForestModel' already exists. Creating a new version of this model...
[2025-05-05T19:50:19.297+0000] {logging_mixin.py:154} WARNING - 2025/05/05 19:50:19 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RandomForestModel, version 6
[2025-05-05T19:50:19.297+0000] {logging_mixin.py:154} WARNING - Created version '6' of model 'RandomForestModel'.
[2025-05-05T19:50:19.298+0000] {warnings.py:109} WARNING - /opt/airflow/dags/Train_Data.py:81: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

[2025-05-05T19:50:19.461+0000] {logging_mixin.py:154} INFO - üèÉ View run rf_diabetes_all_varchar at: http://10.152.183.196:5000/#/experiments/1/runs/61695ea944944285a817d9b3ef4d9cf2
[2025-05-05T19:50:19.461+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T19:50:19.544+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-05T19:50:19.589+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Train_Model, task_id=entrenar_modelo, execution_date=20250505T194928, start_date=20250505T194940, end_date=20250505T195019
[2025-05-05T19:50:19.815+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-05T19:50:19.935+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
