[2025-05-05T13:31:14.811+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load_Data.load_csv_to_postgres manual__2025-05-05T13:25:47.940458+00:00 [queued]>
[2025-05-05T13:31:14.825+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load_Data.load_csv_to_postgres manual__2025-05-05T13:25:47.940458+00:00 [queued]>
[2025-05-05T13:31:14.826+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-05T13:31:14.844+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2025-05-05 13:25:47.940458+00:00
[2025-05-05T13:31:14.868+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2025-05-05T13:31:14.884+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Load_Data', 'load_csv_to_postgres', 'manual__2025-05-05T13:25:47.940458+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/Load_Data.py', '--cfg-path', '/tmp/tmpgtdt1ii1']
[2025-05-05T13:31:14.900+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask load_csv_to_postgres
[2025-05-05T13:31:15.063+0000] {task_command.py:416} INFO - Running <TaskInstance: Load_Data.load_csv_to_postgres manual__2025-05-05T13:25:47.940458+00:00 [running]> on host airflow-worker-5c47d7d789-mw9hk
[2025-05-05T13:31:16.065+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Load_Data' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T13:25:47.940458+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T13:25:47.940458+00:00'
[2025-05-05T13:31:18.054+0000] {logging_mixin.py:154} INFO - Se cargaron 298 filas limpias en la tabla 'diabetic_data'.
[2025-05-05T13:31:18.081+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-05T13:31:18.134+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Load_Data, task_id=load_csv_to_postgres, execution_date=20250505T132547, start_date=20250505T133114, end_date=20250505T133118
[2025-05-05T13:31:18.316+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-05T13:31:18.462+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
