[2025-05-05T19:15:10.529+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T19:14:55.497208+00:00 [queued]>
[2025-05-05T19:15:10.553+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T19:14:55.497208+00:00 [queued]>
[2025-05-05T19:15:10.553+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-05T19:15:10.588+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): entrenar_modelo> on 2025-05-05 19:14:55.497208+00:00
[2025-05-05T19:15:10.618+0000] {standard_task_runner.py:57} INFO - Started process 518 to run task
[2025-05-05T19:15:10.631+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Train_Model', 'entrenar_modelo', 'manual__2025-05-05T19:14:55.497208+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/Train_Data.py', '--cfg-path', '/tmp/tmp17bhh9v8']
[2025-05-05T19:15:10.638+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask entrenar_modelo
[2025-05-05T19:15:10.843+0000] {task_command.py:416} INFO - Running <TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T19:14:55.497208+00:00 [running]> on host airflow-worker-5c47d7d789-mw9hk
[2025-05-05T19:15:11.254+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Train_Model' AIRFLOW_CTX_TASK_ID='entrenar_modelo' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T19:14:55.497208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T19:14:55.497208+00:00'
[2025-05-05T19:15:11.620+0000] {logging_mixin.py:154} INFO - Filas le√≠das: 2086
[2025-05-05T19:15:12.388+0000] {logging_mixin.py:154} WARNING - 2025/05/05 19:15:12 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-05T19:15:12.520+0000] {logging_mixin.py:154} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-05-05T19:15:12.897+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.4s
[2025-05-05T19:15:13.093+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:13.256+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:13.544+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T19:15:13.856+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T19:15:14.125+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T19:15:14.286+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:14.464+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:14.652+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:14.991+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.3s
[2025-05-05T19:15:15.273+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.3s
[2025-05-05T19:15:15.552+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.3s
[2025-05-05T19:15:15.852+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.3s
[2025-05-05T19:15:16.379+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.5s
[2025-05-05T19:15:16.567+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:16.894+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T19:15:17.624+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.7s
[2025-05-05T19:15:18.408+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.8s
[2025-05-05T19:15:18.615+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:18.851+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T19:15:19.123+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.3s
[2025-05-05T19:15:19.649+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.5s
[2025-05-05T19:15:20.415+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.8s
[2025-05-05T19:15:21.056+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.6s
[2025-05-05T19:15:42.023+0000] {logging_mixin.py:154} WARNING - 2025/05/05 19:15:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-05T19:15:42.622+0000] {credentials.py:1124} INFO - Found credentials in environment variables.
[2025-05-05T19:15:44.372+0000] {logging_mixin.py:154} WARNING - 2025/05/05 19:15:44 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RandomForestModel, version 4
[2025-05-05T19:15:44.373+0000] {warnings.py:109} WARNING - /opt/airflow/dags/Train_Data.py:96: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

[2025-05-05T19:15:44.455+0000] {logging_mixin.py:154} INFO - Modelo registrado como RandomForestModel versi√≥n 4 en 'Production'
[2025-05-05T19:15:44.490+0000] {logging_mixin.py:154} INFO - üèÉ View run rf_diabetes_all_varchar at: http://10.152.183.196:5000/#/experiments/1/runs/1a08152cc9ce4067bd610f3ea0ffe712
[2025-05-05T19:15:44.491+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T19:15:44.517+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-05T19:15:44.543+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Train_Model, task_id=entrenar_modelo, execution_date=20250505T191455, start_date=20250505T191510, end_date=20250505T191544
[2025-05-05T19:15:44.665+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-05T19:15:44.702+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
