[2025-05-05T14:09:41.267+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T14:04:16.823142+00:00 [queued]>
[2025-05-05T14:09:41.299+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T14:04:16.823142+00:00 [queued]>
[2025-05-05T14:09:41.299+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-05T14:09:41.359+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): entrenar_modelo> on 2025-05-05 14:04:16.823142+00:00
[2025-05-05T14:09:41.401+0000] {standard_task_runner.py:57} INFO - Started process 415 to run task
[2025-05-05T14:09:41.449+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Train_Model', 'entrenar_modelo', 'manual__2025-05-05T14:04:16.823142+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/Train_Data.py', '--cfg-path', '/tmp/tmphi5r622a']
[2025-05-05T14:09:41.485+0000] {standard_task_runner.py:85} INFO - Job 135: Subtask entrenar_modelo
[2025-05-05T14:09:42.060+0000] {task_command.py:416} INFO - Running <TaskInstance: Train_Model.entrenar_modelo manual__2025-05-05T14:04:16.823142+00:00 [running]> on host airflow-worker-5c47d7d789-mw9hk
[2025-05-05T14:09:42.648+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Train_Model' AIRFLOW_CTX_TASK_ID='entrenar_modelo' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T14:04:16.823142+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T14:04:16.823142+00:00'
[2025-05-05T14:09:43.105+0000] {logging_mixin.py:154} INFO - Filas le√≠das: 2086
[2025-05-05T14:09:45.829+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:09:45 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-05T14:09:46.406+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:09:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/airflow/.local/lib/python3.10/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-05-05T14:09:46.429+0000] {logging_mixin.py:154} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-05-05T14:09:47.002+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.5s
[2025-05-05T14:09:47.214+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T14:09:47.422+0000] {logging_mixin.py:154} INFO - [CV] END .......max_depth=5, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T14:09:47.746+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T14:09:48.334+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.6s
[2025-05-05T14:09:48.653+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=5, n_estimators=100; total time=   0.3s
[2025-05-05T14:09:48.823+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T14:09:49.004+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.2s
[2025-05-05T14:09:49.303+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=5, max_features=10, n_estimators=50; total time=   0.3s
[2025-05-05T14:09:49.889+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.6s
[2025-05-05T14:09:50.346+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.5s
[2025-05-05T14:09:51.154+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=5, max_features=10, n_estimators=100; total time=   0.8s
[2025-05-05T14:09:51.448+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.3s
[2025-05-05T14:09:51.687+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.2s
[2025-05-05T14:09:51.944+0000] {logging_mixin.py:154} INFO - [CV] END ......max_depth=10, max_features=5, n_estimators=50; total time=   0.3s
[2025-05-05T14:09:52.671+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.7s
[2025-05-05T14:09:53.076+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.4s
[2025-05-05T14:09:53.862+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=5, n_estimators=100; total time=   0.8s
[2025-05-05T14:09:54.293+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.4s
[2025-05-05T14:09:54.548+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.3s
[2025-05-05T14:09:55.176+0000] {logging_mixin.py:154} INFO - [CV] END .....max_depth=10, max_features=10, n_estimators=50; total time=   0.6s
[2025-05-05T14:09:55.780+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.6s
[2025-05-05T14:09:56.250+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.5s
[2025-05-05T14:09:57.035+0000] {logging_mixin.py:154} INFO - [CV] END ....max_depth=10, max_features=10, n_estimators=100; total time=   0.8s
[2025-05-05T14:10:01.331+0000] {credentials.py:1124} INFO - Found credentials in environment variables.
[2025-05-05T14:10:02.455+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:10:02 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/airflow/.local/lib/python3.10/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-05-05T14:10:25.970+0000] {logging_mixin.py:154} WARNING - Registered model 'RandomForestModel' already exists. Creating a new version of this model...
[2025-05-05T14:10:26.132+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:10:26 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RandomForestModel, version 2
[2025-05-05T14:10:26.132+0000] {logging_mixin.py:154} WARNING - Created version '2' of model 'RandomForestModel'.
[2025-05-05T14:10:40.061+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:10:40 INFO mlflow.sklearn.utils: Logging the 5 best runs, 3 runs will be omitted.
[2025-05-05T14:10:40.442+0000] {logging_mixin.py:154} INFO - üèÉ View run worried-fox-818 at: http://10.152.183.196:5000/#/experiments/1/runs/db61fb85a4e84f9395f195ff8a7c4bed
[2025-05-05T14:10:40.442+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:10:40.478+0000] {logging_mixin.py:154} INFO - üèÉ View run dashing-crab-211 at: http://10.152.183.196:5000/#/experiments/1/runs/2568200924194bb692e40444cfe430ad
[2025-05-05T14:10:40.479+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:10:40.572+0000] {logging_mixin.py:154} INFO - üèÉ View run casual-dove-682 at: http://10.152.183.196:5000/#/experiments/1/runs/eeeb1ba36cfb450291599bafc7af0e92
[2025-05-05T14:10:40.572+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:10:40.729+0000] {logging_mixin.py:154} INFO - üèÉ View run able-jay-159 at: http://10.152.183.196:5000/#/experiments/1/runs/126ffc7b533449b6ab3dc20d43f94ecc
[2025-05-05T14:10:40.733+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:10:40.754+0000] {logging_mixin.py:154} INFO - üèÉ View run useful-goose-902 at: http://10.152.183.196:5000/#/experiments/1/runs/ba4d06cf3aed4707b4adda2c554fce0b
[2025-05-05T14:10:40.755+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:10:52.573+0000] {logging_mixin.py:154} WARNING - 2025/05/05 14:10:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-05T14:10:52.867+0000] {logging_mixin.py:154} INFO - Modelo entrenado con par√°metros: {'max_depth': 10, 'max_features': 10, 'n_estimators': 50}
[2025-05-05T14:10:52.953+0000] {logging_mixin.py:154} INFO - üèÉ View run rf_diabetes_all_varchar at: http://10.152.183.196:5000/#/experiments/1/runs/90116361afba464e9ba9d8acf78ff7e9
[2025-05-05T14:10:52.953+0000] {logging_mixin.py:154} INFO - üß™ View experiment at: http://10.152.183.196:5000/#/experiments/1
[2025-05-05T14:10:53.059+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-05T14:10:53.099+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Train_Model, task_id=entrenar_modelo, execution_date=20250505T140416, start_date=20250505T140941, end_date=20250505T141053
[2025-05-05T14:10:53.276+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-05T14:10:53.372+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
